### ISSUE TITLE
v1.0.16 error

### ISSUE THREAD

**Issue by BA0GE** [Colossus-Services/bones_ui#1]
[SEVERE]build_web_compilers:ddc on package:bones_ui/bones_ui.ddc.module: Error compiling dartdevc module:bones_ui|lib/bones_ui.ddc.js

packages/bones_ui/src/bones_ui_base.dart:1523:50: Error: Too many positional arguments: 1 allowed, but 2 found.
Try removing the extra positional arguments.
    return _domGenerator.registerElementGenerator(tag, elementGenerator);
                                                 ^
packages/bones_ui/src/bones_ui_base.dart:1532:31: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
      value = domNode.buildDOM(_domGenerator);
                              ^
packages/bones_ui/src/bones_ui_base.dart:1752:27: Error: The getter 'isListValue' isn't defined for the class 'DOMAttribute'.
 - 'DOMAttribute' is from 'package:dom_builder/src/dom_builder_attribute.dart' ('packages/dom_builder/src/dom_builder_attribute.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isListValue'.
          attr.name, attr.isListValue ? attr.values : attr.value);
                          ^^^^^^^^^^^
packages/bones_ui/src/bones_ui_base.dart:1815:27: Error: The getter 'isListValue' isn't defined for the class 'DOMAttribute'.
 - 'DOMAttribute' is from 'package:dom_builder/src/dom_builder_attribute.dart' ('packages/dom_builder/src/dom_builder_attribute.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isListValue'.
          attr.name, attr.isListValue ? attr.values : attr.value);
                          ^^^^^^^^^^^
packages/bones_ui/src/component/button.dart:129:55: Error: The argument type 'Element Function(DOMGenerator<Node>, dynamic, Node, Map<String, DOMAttribute>, Node)' can't be assigned to the parameter type 'ElementGenerator<Node>'.
 - 'Element' is from 'dart:html'.
 - 'DOMGenerator' is from 'package:dom_builder/src/dom_builder_generator.dart' ('packages/dom_builder/src/dom_builder_generator.dart').
 - 'Node' is from 'dart:html'.
 - 'Map' is from 'dart:core'.
 - 'DOMAttribute' is from 'package:dom_builder/src/dom_builder_attribute.dart' ('packages/dom_builder/src/dom_builder_attribute.dart').
 - 'ElementGenerator' is from 'package:dom_builder/src/dom_builder_generator.dart' ('packages/dom_builder/src/dom_builder_generator.dart').
    UIComponent.registerElementGenerator('ui-button', generator);
                                                      ^
[WARNING]build_web_compilers:entrypoint on web/main.dart: Unable to read bones_ui|lib/bones_ui.ddc.js, check your console or the `.dart_tool/build/generated/bones_ui/lib/bones_ui.ddc.js.errors` log file.
[SEVERE]build_web_compilers:entrypoint on web/main.dart: AssetNotFoundException: bones_ui|lib/bones_ui.ddc.js
[INFO] Running build completed, took 10.7s
[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 105ms
[SEVERE] Failed after 10.8s
[INFO] ------------------------------------------------------------------------

**Comment by gmpassos** [comment]
A new version will be published in the next days

**Comment by gmpassos** [comment]
Resolved with version 1.0.20

Thanks for the report.
