### ISSUE TITLE
Running builded app error

### ISSUE THREAD

**Issue by carmas123** [Colossus-Services/bones_ui#5]
When we create a simple project without edit anythink and try to open `index.html` file we got this error into console:

I use this command: `bones_ui create --output . -p project_name_dir=bones_test -p "project_name=Simple Project"`

<img width="980" alt="image" src="https://user-images.githubusercontent.com/6574219/160119736-510d4557-e4e1-440e-97c4-1220f06cf6bf.png">

**Comment by carmas123** [comment]
The problem is in this file: `ui_top_menu.dart`

`<ui-svg width="20px" height="20px" src="${BootstrapIcons.getIconPath('app-indicator')}"></ui-svg>`

I think that the `ui-svg` component is not valid

**Comment by gmpassos** [comment]
I will take a look.

Try to upgrade your dependencies to the last version. The template used in the create command is not updated yet.

When reporting an issue always mention the version of the package and Dart version. Thanks.

**Comment by carmas123** [comment]
Sorry. These are my dependences:

```
dependencies:
  bones_ui: ^2.0.9
  bones_ui_bootstrap: ^2.0.3
  intl_messages: ^2.0.1
  async_field: ^1.0.4
  bootstrap_sass: ^4.5.0
```

This is my Dart:

`Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "macos_x64"`

This is my Flutter:

```
Framework • revision 7e9793dee1 (3 weeks ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2
```

and this is my flutter doctor:

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.65.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

Regards.
